### ISSUE TITLE
Environment variables in codeship-services.yml are not being set in container

### ISSUE THREAD

**Issue by volkanunsal** [codeship/jet-tutorial#20]
Hi, 

There seems to be an issue in the way jet handles environment variables passed via `codeship-services.yml`. Given the following service config:

```yml
js-test:
  build:
    dockerfile: ./dockerfiles/js-test/Dockerfile
  environment:
    CI: 1
```
I expect there to be an environmental variable CI whose value is 1 in the container. But I find that the value of CI is undefined. I can only set a new env var from the Dockerfile, but not from the yml file. I've also tried using the array format, but nothing worked:

```yml
  environment:
    - CI=1
``` 

Can anyone help?
