### ISSUE TITLE
Circular links should be supported

### ISSUE THREAD

**Issue by kreisys** [codeship/jet-tutorial#7]
So I'm having the following use case:

```yaml
app_test:
  image: myapp
  links:
    - selenium
    - selenium_firefox

selenium:
  image: selenium/hub

selenium_firefox:
  image: selenium/node-firefox
  links:
    - selenium:hub
    - app_test
```

So when using the official Selenium images you need to create a container for the "hub" and then create containers for each node and link them to the hub. The link direction has to be node->hub. Now my app needs to be linked to the selenium hub to be able to run selenium tests. It does not need to know about the selenium node (selenium_firefox) but it is linked anyway because links govern which containers will be started.... However, the selenium node does need to know about my app container in order for it to run tests against it. I'm stuck now because with this configuration jet complains:

```
services file error: Circular loop between services app_test and selenium_firefox
```

Unless I'm missing something I understand that links are used as hints to tell jets which services have to be launched along with each service. Apparently this doesn't work for all cases. Also, a potential bug: if I give app_test an alias in the links array (app_test:app for example) then the circular loop is not detected and jet happily runs and ends up in an infinite loop :)
